image: node:18

stages:
  - build

build:
  stage: build
  cache:
    key: build-cache
    paths:
      - node_modules/
      - lib/
      - .npmrc
    policy: push
  script:
    - npm install
    - npm run lint
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - build
