
1.26 KiB
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: fix-byte-order-marker  # Forbid UTF-8 byte-order markers
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.39.0'  # Use the sha / tag you want to point at
    hooks:
    - id: eslint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
